#!/bin/sh

/usr/bin/invoke_app "$@" -C "start_jupyter -t -A -T @tool egfr_igfr_LC.ipynb" \
                        -t EGFR_IGF1R_In_Lung_Cancer \
                        -u anaconda3-5.1 \
                        -e TOOL_PYTHONPATH=/apps/share64/debian7/anaconda/anaconda3-5.1/tools/tellurium/20190823/lib/python3.6/site-packages
